### PR TITLE
refactor: use vinejs instead of zod

### PR DESCRIPTION
**Pull request by Barbapapazes**
Hello,

[@vinejs is just announce](https://twitter.com/AmanVirk1/status/1669226122712686592) and it could be a better validation library (I never used zod but vine is extracted from Adonis and it's a great joy to use).

### CODE REVIEW

**Comment by Barbapapazes** [comment]
Thanks to @thetutlage (thanks 🙏), schemas are now pre-compiled!

[Read more in VineJS docs
](https://vinejs.dev/docs/getting_started#pre-compiling-schema)

https://github.com/Barbapapazes/nuxt-todos-edge/pull/1

**Comment by Barbapapazes** [comment]
> Made changes to actually have utils:
> - `validateParams(event, schema)`
> - `validateQuery(event, schema)`
> - `validateBody(event, schema)`
> 
> As well as `v` object to not have to import vine each time.
> 
> Also added the `throw createError` into it

I'm curious, could you explain why you choose to create validator in API instead using a schema? Is it to keep related code close orto be able to refector using a single function to handle errors? 🤔

**Comment by Atinux** [comment]
Trying to keep each controller into its own file so when you delete it, you don't have to look elsewhere to find dead code.

**Comment by Barbapapazes** [comment]
Thanks! That's make a lot a sens!

**Comment by Atinux** [comment]
Just added the support for pre-compiled schema so you can keep you schema elsewhere if you want, ex:

```ts
const createTodoValidator = v.compile(
  v.object({
    title: v.string().minLength(1).maxLength(100)
  })
)

export default eventHandler(async (event) => {
  const { title } = await validateBody(event, createTodoValidator)
  // ...
})
```

**Comment by Atinux** [comment]
I had to revert this PR since VineJS does not seems to work on Edge runtime:
CleanShot_2023-06-16_at_11 07 512x

**Pull request merged**
